version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pycaltime"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
s3_prefix = "pycaltime"
image_repositories = ["012346180589.dkr.ecr.eu-west-2.amazonaws.com/pycaltime"]