AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for pycaltime

Resources:
  PyCalTimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .aws-sam-build
      PackageType: Zip
      Runtime: python3.12
      Handler: pycaltime.app.lambda_handler
      Timeout: 300
      MemorySize: 1024
      Architectures:
      - arm64
      FunctionUrlConfig:
        AuthType: NONE
      Policies:
        - DynamoDBCrudPolicy:
            TableName: PyCalTimeUserData
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
              Resource: "*"

Outputs:
  Function:
    Description: "pycaltime Function ARN"
    Value: !GetAtt PyCalTimeFunction.Arn
  PyCalTimeFunctionFunctionURL:
    Description: "pycaltime URL HTTP endpoint"
    Value: !GetAtt PyCalTimeFunctionUrl.FunctionUrl