AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for pycaltime

Resources:
  PyCalTimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      PackageType: Image
      Timeout: 300
      MemorySize: 1024
      Architectures:
      - x86_64
      FunctionUrlConfig:
        AuthType: NONE
    Metadata:
      DockerTag: PyCalTimeFunction
      Dockerfile: Dockerfile
      DockerContext: .

Outputs:
  Function:
    Description: "pycaltime Function ARN"
    Value: !GetAtt PyCalTimeFunction.Arn
  PyCalTimeFunctionFunctionURL:
    Description: "pycaltime URL HTTP endpoint"
    Value: !GetAtt PyCalTimeFunctionUrl.FunctionUrl