name: CI-CD-Pipeline

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    types: [opened, edited, reopened]

concurrency:
  group: CICD${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: 3.12

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repository
        uses: actions/checkout@v4

      - name: Setup up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: SAM Validate
        run: sam validate --lint

      - name: Preparing packages for SAM Deploy
        run: pip install . -t .aws-sam-build

      - name: SAM Deploy to AWS Lambda
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
